version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/python:3.7
    working_directory: ~/devops 
    environment:
      CURRENT_DATE: `date -u +”%Y-%m-%dT%H:%M:%SZ”`
    steps:
      # Traer el repositorio desde github
      - checkout
      # Crear el entorno virtual
      - run:
          name: Primer Paso - Instalar dependencias
          command: echo 'Instalando....' |
                   python3 -m venv venv
      - run:
          name: Segundo Paso - Crear artefacto
          command: make
      - run:
          name: Tercer Paso - Validar el programa
          command: python3 app.py
      - store_artifacts:
          path: ./DEPLOY-{$CURRENT_DATE}


