version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/python:3.7
    working_directory: ~/devops 
    environment:
      CURRENT_DATE: "20220329"
    steps:
      # Traer el repositorio desde github
      - checkout
      # Crear el entorno virtual
      - run:
          name: Primer Paso - Instalar dependencias
          command: echo 'Instalando....' |
                   python3 -m venv venv
      # Ejecuta las pruebas
      - run:
          name: Segundo Paso - Ejecuta las pruebas
          command: make
      # Ejecuta prepara el build
      - run:
          name: Segundo Paso - Crear artefacto
          command: make
      - store_artifacts:
          path: ./DEPLOY-{$CURRENT_DATE}


